### ISSUE TITLE
Can not use

### ISSUE THREAD

**Issue by streamentry** [rummelonp/reblog-bot#1]
Hi Mitukiii,

I have updated the config file but it does not work

   couldn't parse YAML at line 10 column 10 (Psych::SyntaxError)

Can you provide a read-me on how to use this.

Thank you,
Hong

**Comment by rummelonp** [comment]
Perhaps it is a problem of Ruby.
http://stackoverflow.com/questions/4980877/rails-error-couldnt-parse-yaml

This app is tumblr bot that random reblog from following tumblelogs.

Copy config/config.yml.sample to config/config.yml, and edit this to likes to yourself.
Can be set to notes threshold, kind of post & cron interval.

After save config file, can generate cron with "whenever" command.

Thanks.

**Comment by rummelonp** [comment]
Sorry, my sample is wrong.
Pushed that fix version.

**Comment by streamentry** [comment]
Thank you. I'll try it
